// This file was generated by rdfs2cs.
// The class below represents the type http://xmlns.com/foaf/0.1/Agent.

using System;
using SemWeb;

public sealed class FOAFAgent {

	Entity entity;

	public FOAFAgent(Entity entity) { this.entity = entity; }

	public static implicit operator FOAFAgent(Entity entity) { return new FOAFAgent(entity); }

	public static implicit operator Entity(FOAFAgent entity) { return entity; }

	private static readonly string mboxProperty = "http://xmlns.com/foaf/0.1/mbox";
	public Resource[] mbox {
		get {
			return entity[mboxProperty, true];
		}
	}

	private static readonly string mbox_sha1sumProperty = "http://xmlns.com/foaf/0.1/mbox_sha1sum";
	public Resource[] mbox_sha1sum {
		get {
			return entity[mbox_sha1sumProperty, true];
		}
	}

	private static readonly string genderProperty = "http://xmlns.com/foaf/0.1/gender";
	public Resource gender {
		get {
			Resource[] resources = entity[genderProperty, true];
			if (resources.Length == 0) return null; else return resources[0];
		}
	}

	private static readonly string jabberIDProperty = "http://xmlns.com/foaf/0.1/jabberID";
	public Resource[] jabberID {
		get {
			return entity[jabberIDProperty, true];
		}
	}

	private static readonly string aimChatIDProperty = "http://xmlns.com/foaf/0.1/aimChatID";
	public Resource[] aimChatID {
		get {
			return entity[aimChatIDProperty, true];
		}
	}

	private static readonly string icqChatIDProperty = "http://xmlns.com/foaf/0.1/icqChatID";
	public Resource[] icqChatID {
		get {
			return entity[icqChatIDProperty, true];
		}
	}

	private static readonly string yahooChatIDProperty = "http://xmlns.com/foaf/0.1/yahooChatID";
	public Resource[] yahooChatID {
		get {
			return entity[yahooChatIDProperty, true];
		}
	}

	private static readonly string msnChatIDProperty = "http://xmlns.com/foaf/0.1/msnChatID";
	public Resource[] msnChatID {
		get {
			return entity[msnChatIDProperty, true];
		}
	}

	private static readonly string weblogProperty = "http://xmlns.com/foaf/0.1/weblog";
	public Resource[] weblog {
		get {
			return entity[weblogProperty, true];
		}
	}

	private static readonly string tipjarProperty = "http://xmlns.com/foaf/0.1/tipjar";
	public Resource[] tipjar {
		get {
			return entity[tipjarProperty, true];
		}
	}

	private static readonly string madeProperty = "http://xmlns.com/foaf/0.1/made";
	public Resource[] made {
		get {
			return entity[madeProperty, true];
		}
	}

	private static readonly string holdsAccountProperty = "http://xmlns.com/foaf/0.1/holdsAccount";
	public Resource[] holdsAccount {
		get {
			return entity[holdsAccountProperty, true];
		}
	}

	private static readonly string nameProperty = "http://xmlns.com/foaf/0.1/name";
	public Resource[] name {
		get {
			return entity[nameProperty, true];
		}
	}

	private static readonly string homepageProperty = "http://xmlns.com/foaf/0.1/homepage";
	public Resource[] homepage {
		get {
			return entity[homepageProperty, true];
		}
	}

	private static readonly string makerProperty = "http://xmlns.com/foaf/0.1/maker";
	public Resource[] maker {
		get {
			return entity[makerProperty, true];
		}
	}

	private static readonly string depictionProperty = "http://xmlns.com/foaf/0.1/depiction";
	public Resource[] depiction {
		get {
			return entity[depictionProperty, true];
		}
	}

	private static readonly string fundedByProperty = "http://xmlns.com/foaf/0.1/fundedBy";
	public Resource[] fundedBy {
		get {
			return entity[fundedByProperty, true];
		}
	}

	private static readonly string logoProperty = "http://xmlns.com/foaf/0.1/logo";
	public Resource[] logo {
		get {
			return entity[logoProperty, true];
		}
	}

	private static readonly string pageProperty = "http://xmlns.com/foaf/0.1/page";
	public Resource[] page {
		get {
			return entity[pageProperty, true];
		}
	}

	private static readonly string themeProperty = "http://xmlns.com/foaf/0.1/theme";
	public Resource[] theme {
		get {
			return entity[themeProperty, true];
		}
	}

	private static readonly string makerOfProperty = "http://xmlns.com/foaf/0.1/maker";
	public Resource[] makerOf {
		get {
			return entity[makerOfProperty, false];
		}
	}

	private static readonly string memberOfProperty = "http://xmlns.com/foaf/0.1/member";
	public Resource[] memberOf {
		get {
			return entity[memberOfProperty, false];
		}
	}

	private static readonly string mboxOfProperty = "http://xmlns.com/foaf/0.1/mbox";
	public Resource mboxOf {
		get {
			Resource[] resources = entity[mboxOfProperty, false];
			if (resources.Length == 0) return null; else return resources[0];
		}
	}

	private static readonly string madeOfProperty = "http://xmlns.com/foaf/0.1/made";
	public Resource[] madeOf {
		get {
			return entity[madeOfProperty, false];
		}
	}

	private static readonly string depictsOfProperty = "http://xmlns.com/foaf/0.1/depicts";
	public Resource[] depictsOf {
		get {
			return entity[depictsOfProperty, false];
		}
	}

	private static readonly string topic_interestOfProperty = "http://xmlns.com/foaf/0.1/topic_interest";
	public Resource[] topic_interestOf {
		get {
			return entity[topic_interestOfProperty, false];
		}
	}

	private static readonly string currentProjectOfProperty = "http://xmlns.com/foaf/0.1/currentProject";
	public Resource[] currentProjectOf {
		get {
			return entity[currentProjectOfProperty, false];
		}
	}

	private static readonly string pastProjectOfProperty = "http://xmlns.com/foaf/0.1/pastProject";
	public Resource[] pastProjectOf {
		get {
			return entity[pastProjectOfProperty, false];
		}
	}

	private static readonly string fundedProperty = "http://xmlns.com/foaf/0.1/fundedBy";
	public Resource[] funded {
		get {
			return entity[fundedProperty, false];
		}
	}

	private static readonly string logoOfProperty = "http://xmlns.com/foaf/0.1/logo";
	public Resource[] logoOf {
		get {
			return entity[logoOfProperty, false];
		}
	}

	private static readonly string topicOfProperty = "http://xmlns.com/foaf/0.1/topic";
	public Resource[] topicOf {
		get {
			return entity[topicOfProperty, false];
		}
	}

	private static readonly string primaryTopicOfProperty = "http://xmlns.com/foaf/0.1/primaryTopic";
	public Resource[] primaryTopicOf {
		get {
			return entity[primaryTopicOfProperty, false];
		}
	}

	private static readonly string themeOfProperty = "http://xmlns.com/foaf/0.1/theme";
	public Resource[] themeOf {
		get {
			return entity[themeOfProperty, false];
		}
	}

}
