PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bill: <http://www.rdfabout.com/rdf/schema/usbill/>
SELECT *
FROM <http://test/x>
#FROM NAMED <http://test/y>
WHERE {
#GRAPH ?x {
 ?bill a bill:SenateBill .
 ?bill bill:congress "109" .
 ?bill bill:number "1024" .
 ?bill bill:sponsor ?person .
 ?person foaf:name ?name .
#}
}
